---
# defaults file for kvm_provision
base_image_name: focal-server-cloudimg-amd64-disk-kvm.img
base_image_url: https://cloud-images.ubuntu.com/focal/current/{{ base_image_name }}
base_image_sha: 4363408f763cf95c606a88dfd9e7b972f06a96dadd7ae89ce7b633dccd9a3b53
libvirt_pool_dir: "/var/lib/libvirt/images"
vm_name: f34-dev
vm_vcpus: 2
vm_ram_mb: 2048
vm_net: default
vm_root_pass: test123
cleanup_tmp: no
ssh_key: /root/.ssh/id_rsa.pub
